# https://devdocs.prestashop.com/8/modules/concepts/services/
services:
    PrestaShop\Module\IqitProductVariants\Form\Modifier\ProductFormModifier:
        class: PrestaShop\Module\IqitProductVariants\Form\Modifier\ProductFormModifier
        public: true
        autowire: true
        arguments:
            - '@form.form_builder_modifier'
            - "@=service('prestashop.adapter.legacy.context').getContext()"
            - '@translator'
            - '@router'
            - '@=service("prestashop.adapter.legacy.context").getEmployeeLanguageIso()'

    PrestaShop\Module\IqitProductVariants\Form\Product\ProductFormDataHandler:
        class: PrestaShop\Module\IqitProductVariants\Form\Product\ProductFormDataHandler
        public: true

    PrestaShop\Module\IqitProductVariants\Repository\ProductVariantsRepository:
        class: PrestaShop\Module\IqitProductVariants\Repository\ProductVariantsRepository
        public: true
        arguments:
            - '@=service("prestashop.adapter.legacy.context").getContext().language.id'
            - '@=service("prestashop.adapter.legacy.context").getContext().shop.id'

    PrestaShop\Module\IqitProductVariants\Presenter\ProductVariantsPresenter:
        class: PrestaShop\Module\IqitProductVariants\Presenter\ProductVariantsPresenter 
        public: true
        autowire: true
        arguments:
            - '@=service("prestashop.adapter.legacy.context")'